name: quality

on:
  pull_request:
    branches: [ "main" ]

jobs:
  quality:
    runs-on: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v4

    - name: Conventional Commit Linter
      uses: ahmadnassri/action-commit-lint@v2

    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Go Test
      run: make test
